[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "allocation"
version = "0.1"
requires-python = ">=3.9"
dependencies = [
    "sqlalchemy",
    "flask",
    "psycopg2-binary",
    "tenacity",
    "requests",
    "redis",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-icdiff",
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--tb=short"
log_cli = true
log_cli_level = "DEBUG"

[tool.mypy]
ignore_missing_imports = false
mypy_path = "./src"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["pytest.*", "sqlalchemy.*"]
ignore_missing_imports = true
